public import W3C_CSS_Color
public import W3C_CSS_Shared
public import W3C_CSS_Values

/// The CSS accent-color property sets the accent color for user-interface controls generated by some elements.
///
/// Browsers that support accent-color currently apply it to the following HTML elements:
/// - `<input type="checkbox">`
/// - `<input type="radio">`
/// - `<input type="range">`
/// - `<progress>`
///
/// Each user agent has an accent color, with variations to ensure legibility and contrast.
/// That accent color is not used by every user-interface control nor in every state of the control.
/// The accent-color is only applied to user-interface controls that use an accent color in the states
/// where it is applicable.
///
/// - SeeAlso: [MDN Web Docs on accent-color](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color)
public enum AccentColor: Property, ColorConvertible {
    public static let property: String = "accent-color"

    /// The browser's default accent color
    case auto

    /// A specific color to use as the accent color
    case color(W3C_CSS_Values.Color)

    /// Global values
    case global(Global)
}

/// CSS Output conversion
extension AccentColor {
    /// Converts the accent color to its CSS string representation
    public var description: String {
        switch self {
        case .auto:
            return "auto"
        case .color(let color):
            return color.description
        case .global(let global):
            return global.description
        }
    }
}
